# This is a config for E2B sandbox template.
# You can use template ID (tvlku9lyud0ynzeydses) or template name (vibe-next-victor-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-next-victor-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-victor-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-victor-2')

team_id = "96eca3bd-e4cd-4de0-b4f8-53c82b230300"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-victor-2"
template_id = "tvlku9lyud0ynzeydses"
